import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, relative, resolve } from "node:path";
import ts from "typescript";

const mode = process.argv.includes("--check") ? "check" : "write";
const workspaceRoot = process.cwd();
const packages = [
  {
    name: "@viewrig/core",
    entry: "packages/core/src/index.ts",
    report: "api-reports/core.api.md"
  }
];

function normalizePath(path) {
  return path.replaceAll("\\", "/");
}

function readSource(path) {
  const source = readFileSync(path, "utf8");
  return ts.createSourceFile(path, source, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS);
}

function hasExportModifier(node) {
  return node.modifiers?.some((modifier) => modifier.kind === ts.SyntaxKind.ExportKeyword) ?? false;
}

function collectExportedNames(sourceFile) {
  const exports = [];

  for (const node of sourceFile.statements) {
    if (!hasExportModifier(node)) {
      continue;
    }

    if (ts.isInterfaceDeclaration(node)) {
      exports.push({ kind: "interface", name: node.name.text });
    } else if (ts.isTypeAliasDeclaration(node)) {
      exports.push({ kind: "type", name: node.name.text });
    } else if (ts.isClassDeclaration(node) && node.name !== undefined) {
      exports.push({ kind: "class", name: node.name.text });
    } else if (ts.isFunctionDeclaration(node) && node.name !== undefined) {
      exports.push({ kind: "function", name: node.name.text });
    } else if (ts.isEnumDeclaration(node)) {
      exports.push({ kind: "enum", name: node.name.text });
    } else if (ts.isVariableStatement(node)) {
      const declarationKind = node.declarationList.flags & ts.NodeFlags.Const ? "const" : "let";
      for (const declaration of node.declarationList.declarations) {
        if (ts.isIdentifier(declaration.name)) {
          exports.push({ kind: declarationKind, name: declaration.name.text });
        }
      }
    }
  }

  return exports.sort((a, b) => a.name.localeCompare(b.name) || a.kind.localeCompare(b.kind));
}

function collectExportStars(sourceFile) {
  const modules = [];

  for (const node of sourceFile.statements) {
    if (
      ts.isExportDeclaration(node) &&
      node.exportClause === undefined &&
      node.moduleSpecifier !== undefined &&
      ts.isStringLiteral(node.moduleSpecifier)
    ) {
      modules.push(node.moduleSpecifier.text);
    }
  }

  return modules;
}

function renderExportList(exports) {
  if (exports.length === 0) {
    return "- none";
  }

  return exports.map((item) => `- ${item.kind} \`${item.name}\``).join("\n");
}

function renderReport(packageConfig) {
  const entryPath = resolve(workspaceRoot, packageConfig.entry);
  const entrySource = readSource(entryPath);
  const lines = [
    `# API Report: ${packageConfig.name}`,
    "",
    "> Generated by `pnpm api:report`. Update this file intentionally when public exports change.",
    "",
    `Entry: \`${normalizePath(packageConfig.entry)}\``,
    "",
    "## Entry Declarations",
    "",
    renderExportList(collectExportedNames(entrySource)),
    "",
    "## Exported Modules"
  ];

  for (const specifier of collectExportStars(entrySource)) {
    const modulePath = resolve(dirname(entryPath), `${specifier}.ts`);
    const source = readSource(modulePath);
    lines.push("", `### \`${specifier}\``, "", renderExportList(collectExportedNames(source)));
  }

  lines.push("");
  return lines.join("\n");
}

let failed = false;

for (const packageConfig of packages) {
  const report = renderReport(packageConfig);
  const reportPath = resolve(workspaceRoot, packageConfig.report);

  if (mode === "write") {
    mkdirSync(dirname(reportPath), { recursive: true });
    writeFileSync(reportPath, report, "utf8");
    console.log(`wrote ${relative(workspaceRoot, reportPath)}`);
    continue;
  }

  let current = "";
  try {
    current = readFileSync(reportPath, "utf8");
  } catch {
    console.error(`missing API report: ${relative(workspaceRoot, reportPath)}`);
    failed = true;
    continue;
  }

  if (current !== report) {
    console.error(`API report is stale: ${relative(workspaceRoot, reportPath)}`);
    console.error("Run `pnpm api:report` and review the diff.");
    failed = true;
  }
}

if (failed) {
  process.exit(1);
}

if (mode === "check") {
  console.log("api report check passed");
}
